// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eumfdxgcqenpptjytqmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1bWZkeGdjcWVucHB0anl0cW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDU2OTMsImV4cCI6MjA3NDM4MTY5M30.6Gct9fFUj0DBG4c2-AFmyIr_8tfjnX4KfpqCZgQ1Hk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});